apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
  - name: syntaxnow-assets-config
    behavior: create
    files:
      - values-prod.yaml

patches:
  - path: patch-image.yaml
