apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-f1-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/acme-http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - test-f1-qa.syntaxnow.com
    secretName: test-f1-tls-cert
  rules:
  - host: test-f1-qa.syntaxnow.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test-f1
            port:
              number: 80
