apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vm-0656-dev-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/syntaxnow-labs/gitops.git
        revision: main
        files:
          - path: clusters/vm-0656/apps-dev.yaml

  template:
    metadata:
      name: "{{app}}-dev"

    spec:
      project: default

      source:
        repoURL: https://github.com/syntaxnow-labs/gitops.git
        targetRevision: main
        path: "apps/{{app}}/overlays/dev"

      destination:
        server: https://kubernetes.default.svc
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
