apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applicationset-prod.yaml
  - applicationset-dev.yaml
  - applicationset-qa.yaml
  - apps-dev-infra.yaml
  - apps-qa-infra.yaml
  - apps-prod-infra.yaml