apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - ingress.yaml
  # no secrets for this app

configMapGenerator:
  - name: sky-ledger-ui-config
    behavior: create
    envs:
      - values-dev.env

patches:
  - path: patch-image.yaml
