apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: sky-ledger-ui-config
    behavior: create
    files:
      - values-dev.yaml

patches:
  - path: patch-image.yaml
