apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-ledger-services
  labels:
    app: sky-ledger-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky-ledger-services
  template:
    metadata:
      labels:
        app: sky-ledger-services
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: sky-ledger-services
          image: ghcr.io/syntaxnow-labs/sky-ledger-services:latest
          ports:
            - containerPort: 9090
          envFrom:
            - configMapRef:
                name: sky-ledger-services-config
            - secretRef:
                name: sky-ledger-service-secrets
