apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/syntaxnow-labs/sample-react-app
    newTag: dev

configMapGenerator:
  - name: sample-react-config
    behavior: create
    files:
      - values-dev.yaml
