apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oneplatform-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/acme-http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - oneplatform-dev.syntaxnow.com
    secretName: oneplatform-tls-cert
  rules:
  - host: oneplatform-dev.syntaxnow.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oneplatform
            port:
              number: 80
