apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-prod

resources:
  - ../../base
  - ingress.yaml
  - secrets.yaml

configMapGenerator:
  - name: sky-ledger-services-config
    behavior: create
    envs:
      - values-prod.env

patches:
  - path: patch-image.yaml
