apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-qa

resources:
  - ../../base
  - ingress.yaml
  # no secrets for this app

configMapGenerator:
  - name: mock-api-service-config
    behavior: create
    envs:
      - values-qa.env

patches:
  - path: patch-image.yaml
