apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
  - name: mock-api-service-config
    behavior: create
    files:
      - values-qa.yaml

patches:
  - path: patch-image.yaml
