apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-qa

resources:
  - ../../base
  - secrets.yaml
  - ingress.yaml

configMapGenerator:
  - name: sky-ledger-services-config
    behavior: create
    files:
      - values-qa.yaml

patches:
  - path: patch-image.yaml
