apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-react-app
  template:
    metadata:
      labels:
        app: sample-react-app
    spec:
      containers:
        - name: sample-react-app
          image: ghcr.io/syntaxnow-labs/sample-react-app:latest
          ports:
            - containerPort: 80
