apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

configMapGenerator:
  - name: poc-apache-arrow-config
    behavior: create
    files:
      - values-dev.yaml

patches:
  - path: patch-image.yaml
