apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps-dev

resources:
  - ../../base
  - secrets.yaml
  - namespace.yaml
  - ingress.yaml

configMapGenerator:
  - name: sky-ledger-services-config
    behavior: create
    envs:
      - values-dev.env

patches:
  - path: patch-image.yaml
