apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntaxnow-assets
  labels:
    app: syntaxnow-assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syntaxnow-assets
  template:
    metadata:
      labels:
        app: syntaxnow-assets
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: syntaxnow-assets
          image: ghcr.io/syntaxnow-labs/syntaxnow-assets:latest
          ports:
            - containerPort: 9090
