apiVersion: apps/v1
kind: Deployment
metadata:
  name: syntaxnow-identity-service
  labels:
    app: syntaxnow-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syntaxnow-identity-service
  template:
    metadata:
      labels:
        app: syntaxnow-identity-service
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: syntaxnow-identity-service
          image: ghcr.io/syntaxnow-labs/syntaxnow-identity-service:latest
          ports:
            - containerPort: 9090

          envFrom:
            - secretRef:
                name: identity-secrets

          volumeMounts:
            - name: firebase-volume
              mountPath: /app/secrets
              readOnly: true

      volumes:
        - name: firebase-volume
          secret:
            secretName: identity-secrets
            items:
              - key: firebase.json
                path: firebase.json
